apiVersion: tribefire.cloud/v1alpha1
kind: TribefireRuntime
metadata:
  name: tfdemo-stable
  namespace: ns
spec:
  backend:
    type: etcd
  components:
  - env:
    - name: CI_RUN_URL
      value: internal
    image: docker.artifactory.braintribe.com/releases/cortex/tribefire-demo/2.0/tribefire-control-center
    imageTag: latest
    name: tribefire-control-center
    resources:
      limits:
        cpu: "1"
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 192Mi
    type: control-center
  - env:
    - name: CI_RUN_URL
      value: internal
    image: docker.artifactory.braintribe.com/releases/cortex/tribefire-demo/2.0/tribefire-explorer
    imageTag: latest
    name: tribefire-explorer
    resources:
      limits:
        cpu: "1"
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 192Mi
    type: explorer
  - env:
    - name: CI_RUN_URL
      value: internal
    image: docker.artifactory.braintribe.com/releases/cortex/tribefire-demo/2.0/tribefire-master
    imageTag: latest
    name: tribefire-master
    resources:
      limits:
        cpu: "3"
        memory: 3Gi
      requests:
        cpu: 500m
        memory: 1Gi
    type: services
  databaseType: local
  domain: your.domain

