apiVersion: tribefire.cloud/v1alpha1
kind: TribefireRuntime
metadata:
  labels:
    app: adx
    stage: dev
  name: adx-dev
  namespace: adx
spec:
  backend:
    parameters:
    - name: url
      value: http://tf-etcd-cluster-client:2379
    type: etcd
  components:
  - apiPath: /control-center
    image: docker.artifactory.braintribe.com/releases/adx/2.6.278-p1/tribefire-control-center
    imageTag: latest
    logJson: "true"
    logLevel: INFO
    name: tribefire-control-center
    protocol: https
    replicas: 1
    resources: {}
    type: control-center
  - apiPath: /explorer
    image: docker.artifactory.braintribe.com/releases/adx/2.6.278-p1/tribefire-explorer
    imageTag: latest
    logJson: "true"
    logLevel: INFO
    name: tribefire-explorer
    protocol: https
    replicas: 1
    resources: {}
    type: explorer
  - env:
    - name: ADX_ENABLE_HEALTH_CHECK_ERROR_MESSAGES
      value: "false"
    - name: ADX_DEFAULT_STORAGE_CONTENT_TYPE
      value: s3
    - name: ADX_DEFAULT_STORAGE_CACHE_TYPE
      value: s3
    - name: ADX_DEFAULT_S3_BUCKETNAME
      value: __S3_BUCKET_NAME__
    - name: ADX_DEFAULT_S3_PATH_PREFIX
      value: adx
    - name: ADX_DEFAULT_S3_ACCESS_KEY
      value: ${decrypt('__S3_ACCESS_KEY_ENCRYPTED__')}
    - name: ADX_DEFAULT_S3_SECRET_ACCESS_KEY
      value: ${decrypt('__S3_SECRET_ENCRYPTED__')}
    - name: ADX_DEFAULT_S3_REGION
      value: eu_central_1
    - name: ADX_DEFAULT_CACHE_S3_BUCKETNAME
      value: __S3_BUCKET_NAME__
    - name: ADX_DEFAULT_CACHE_S3_PATH_PREFIX
      value: adx-cache
    - name: ADX_DEFAULT_CACHE_S3_ACCESS_KEY
      value: ${decrypt('__S3_ACCESS_KEY_ENCRYPTED__')}
    - name: ADX_DEFAULT_CACHE_S3_SECRET_ACCESS_KEY
      value: ${decrypt('__S3_SECRET_ENCRYPTED__')}
    - name: ADX_DEFAULT_CACHE_S3_REGION
      value: eu_central_1
    - name: ADX_DEFAULT_DB_HOST
      value: __DATABASE_HOST__
    - name: ADX_DEFAULT_DB_NAME
      value: __DATABASE_NAME__
    - name: ADX_DEFAULT_DB_PASSWORD
      value: ${decrypt('__DB_PASSWORD_ENCRYPTED__')}
    - name: ADX_DEFAULT_DB_TYPE
      value: PostgreSQL
    - name: ADX_DEFAULT_DB_USER
      value: __DB_USER__
    - name: ADX_INIT_DEFAULT_REPOSITORY
      value: "true"
    - name: ADX_WEBREADER_BASE_URL
      value: ${TRIBEFIRE_PUBLIC_SERVICES_URL}/../web-reader
    - name: ADX_WB_COMMON_RESOURCES_PATH
      value: ${TRIBEFIRE_STORAGE_DIR}/databases/access.adx.content.wb/resources
    - name: CONV_DB_PASSWORD
      value: __DB_PASSWORD_ENCRYPTED__
    - name: CONV_DB_URL
      value: jdbc:postgresql://__DATABASE_HOST__:5432/__DATABASE_NAME__
    - name: CONV_DB_USER
      value: __DB_USER__
    - name: CONV_INITIALIZE
      value: "true"
    - name: CONV_STORAGE_TYPE
      value: db
    - name: DOCUMENTS_REMOTE_CONVERSION
      value: "false"
    - name: ELASTIC_CREATE_DEMO_ACCESS
      value: "false"
    - name: ELASTIC_RUN_SERVICE
      value: "true"
    - name: ELASTIC_SERVICE_DATA_PATH
      value: /opt/tribefire/mnt/elastic
    - name: TRIBEFIRE_ADDITIONAL_OPTIONS
      value: -Xms1g -Xmx5g
    - name: TRIBEFIRE_LANDING_PAGE_URL
      value: component/home
    image: docker.artifactory.braintribe.com/releases/adx/2.6.278-p1/tribefire-master
    imageTag: latest
    logJson: "true"
    logLevel: FINE
    name: tribefire-master
    protocol: https
    replicas: 1
    resources:
      limits:
        cpu: "5"
        memory: 8Gi
      requests:
        cpu: 500m
        memory: 3Gi
    type: services
  - apiPath: /web-reader
    image: docker.artifactory.braintribe.com/releases/adx/2.6.278-p1/tribefire-web-reader
    imageTag: latest
    logJson: "true"
    logLevel: INFO
    name: tribefire-web-reader
    protocol: https
    replicas: 1
    resources: {}
    type: web-reader
  databaseType: local
  dcsaConfig:
    credentialsSecretRef:
      name: database-credentials
    instanceDescriptor: jdbc:postgresql://__DATABASE_HOST__:5432/__DATABASE_NAME__
  domain: __DOMAIN__

