#
# Used to deploy in the default namespace - this MUST not be done until the general design decision to deploy in a particular namespace is changed
#
# Until this is not done: THIS IS NOT ALLOWED TO BE DEPLOYED
#
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tfcloud-operator
rules:
- apiGroups:
  - tribefire.cloud
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - "*"

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tfcloud-operator
subjects:
- kind: ServiceAccount
  name: tfcloud-operator
  namespace: default
roleRef:
  kind: ClusterRole
  name: tfcloud-operator
  apiGroup: rbac.authorization.k8s.io
