---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traefik-ingress-controller
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traefik-ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-ingress-controller
subjects:
- kind: ServiceAccount
  name: traefik-ingress-controller
  namespace: kube-system
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: traefik-ingress
  name: traefik-ingress-service
  namespace: kube-system
spec:
  ports:
  - name: web
    nodePort: 30080
    port: 80
    protocol: TCP
  - name: admin
    nodePort: 30880
    port: 8080
    protocol: TCP
  selector:
    k8s-app: traefik-ingress
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: traefik-ingress
  name: traefik-ingress-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: traefik-ingress
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress
    spec:
      containers:
      - args:
        - --api
        - --kubernetes
        - --metrics
        - --metrics.prometheus
        - --metrics.prometheus.entrypoint=traefik
        - --ping=true
        - --logLevel=INFO
        - --respondingtimeouts.idletimeout=10m0s
        image: traefik:1.7.30
        name: traefik-ingress
      serviceAccountName: traefik-ingress-controller
